mutation CreateMyProfile(
  $username: String!
  $email: String!
  $avatarUrl: String
) @auth(level: USER) {
  user_insert(
    data: {
      firebaseUid_expr: "auth.uid"
      username: $username
      email: $email
      avatarUrl: $avatarUrl
    }
  )
}

mutation UpdateMyProfile(
  $username: String!
  $email: String!
  $avatarUrl: String
  $bio: String
) @auth(level: USER) {
  user_updateMany(
    where: { firebaseUid: { eq_expr: "auth.uid" } }
    data: {
      username: $username
      email: $email
      avatarUrl: $avatarUrl
      bio: $bio
      updatedAt_expr: "request.time"
    }
  )
}
