/**
 * Packs unicode para el compositor de Publicaciones.
 * Son caracteres Unicode estándar (no recortes ni redibujos de Apple/WhatsApp).
 * El tinte visual vive solo en `.lb-unicode-emoji` del selector.
 */
import { FLAG_PICKER_EMOJIS } from './circleFlags';

export type UnicodeEmoji = {
  char: string;
  label: string;
};

export type UnicodeEmojiCategory = {
  id: string;
  label: string;
  icon: string;
  emojis: UnicodeEmoji[];
};

function pack(pairs: Array<[string, string]>): UnicodeEmoji[] {
  return pairs.map(([char, label]) => ({ char, label }));
}

const FACES = pack([
  ['😀', 'sonrisa'],
  ['😃', 'sonrisa ojos'],
  ['😄', 'sonrisa abierta'],
  ['😁', 'dientes'],
  ['😆', 'risa'],
  ['😅', 'sudor'],
  ['🤣', 'lágrimas risa'],
  ['😂', 'llora risa'],
  ['🙂', 'leve'],
  ['🙃', 'al revés'],
  ['😉', 'guiño'],
  ['😊', 'rubor'],
  ['😇', 'ángel'],
  ['🥰', 'enamorado'],
  ['😍', 'ojos corazón'],
  ['🤩', 'estrellas'],
  ['😘', 'beso'],
  ['😗', 'beso serio'],
  ['☺️', 'sonrisa suave'],
  ['😚', 'beso ojos'],
  ['😙', 'beso sonrisa'],
  ['🥲', 'sonrisa lágrima'],
  ['😋', 'ñam'],
  ['😛', 'lengua'],
  ['😜', 'lengua guiño'],
  ['🤪', 'loco'],
  ['😝', 'lengua cerrado'],
  ['🤑', 'dinero'],
  ['🤗', 'abrazo'],
  ['🤭', 'risa tapada'],
  ['🤫', 'silencio'],
  ['🤔', 'piensa'],
  ['🤐', 'zipper'],
  ['🤨', 'ceja'],
  ['😐', 'neutral'],
  ['😑', 'sin expresión'],
  ['😶', 'sin boca'],
  ['😏', 'picardía'],
  ['😒', 'inseguro'],
  ['🙄', 'ojos arriba'],
  ['😬', 'mueca'],
  ['🤥', 'mentira'],
  ['😌', 'alivio'],
  ['😔', 'pensativo'],
  ['😪', 'somnoliento'],
  ['🤤', 'babeo'],
  ['😴', 'duerme'],
  ['😷', 'mascarilla'],
  ['🤒', 'fiebre'],
  ['🤕', 'herido'],
  ['🤢', 'náusea'],
  ['🤮', 'vómito'],
  ['🤧', 'estornudo'],
  ['🥵', 'calor'],
  ['🥶', 'frío'],
  ['🥴', 'mareado'],
  ['😵', 'dizzy'],
  ['🤯', 'explota'],
  ['🤠', 'vaquero'],
  ['🥳', 'fiesta'],
  ['🥸', 'disfraz'],
  ['😎', 'cool'],
  ['🤓', 'nerd'],
  ['🧐', 'monóculo'],
  ['😕', 'confundido'],
  ['😟', 'preocupado'],
  ['🙁', 'triste leve'],
  ['☹️', 'triste'],
  ['😮', 'sorpresa'],
  ['😯', 'asombro'],
  ['😲', 'impactado'],
  ['😳', 'sonrojo'],
  ['🥺', 'piedad'],
  ['😦', 'boquiabierto'],
  ['😧', 'angustia'],
  ['😨', 'miedo'],
  ['😰', 'sudor frío'],
  ['😥', 'alivio triste'],
  ['😢', 'llora'],
  ['😭', 'llanto'],
  ['😱', 'grito'],
  ['😖', 'angustiado'],
  ['😣', 'esfuerzo'],
  ['😞', 'decepcionado'],
  ['😓', 'sudor frío 2'],
  ['😩', 'agotado'],
  ['😫', 'cansado'],
  ['🥱', 'bostezo'],
  ['😤', 'humos'],
  ['😡', 'enojado'],
  ['😠', 'furioso'],
  ['🤬', 'insulto'],
  ['😈', 'diablito feliz'],
  ['👿', 'diablito enojado'],
  ['💀', 'calavera'],
  ['☠️', 'calavera huesos'],
  ['💩', 'poop'],
  ['🤡', 'payaso'],
  ['👹', 'ogro'],
  ['👺', 'duende'],
  ['👻', 'fantasma'],
  ['👽', 'alien'],
  ['👾', 'invader'],
  ['🤖', 'robot'],
  ['😺', 'gato sonrisa'],
  ['😸', 'gato risa'],
  ['😹', 'gato lágrimas'],
  ['😻', 'gato corazón'],
  ['😼', 'gato irónico'],
  ['😽', 'gato beso'],
  ['🙀', 'gato grito'],
  ['😿', 'gato llora'],
  ['😾', 'gato enojado'],
  ['🙈', 'mono no ve'],
  ['🙉', 'mono no oye'],
  ['🙊', 'mono no habla'],
]);

const HANDS = pack([
  ['👋', 'hola'],
  ['🤚', 'mano alzada'],
  ['🖐️', 'palma'],
  ['✋', 'stop'],
  ['🖖', 'vulcano'],
  ['👌', 'ok'],
  ['🤌', 'pinza'],
  ['🤏', 'poco'],
  ['✌️', 'paz'],
  ['🤞', 'suerte'],
  ['🤟', 'te quiero'],
  ['🤘', 'rock'],
  ['🤙', 'lláname'],
  ['👈', 'izquierda'],
  ['👉', 'derecha'],
  ['👆', 'arriba'],
  ['🖕', 'insulto mano'],
  ['👇', 'abajo'],
  ['☝️', 'índice'],
  ['👍', 'like'],
  ['👎', 'dislike'],
  ['✊', 'puño'],
  ['👊', 'golpe'],
  ['🤛', 'puño izq'],
  ['🤜', 'puño der'],
  ['👏', 'aplauso'],
  ['🙌', 'celebrar'],
  ['👐', 'abiertas'],
  ['🤲', 'ofrenda'],
  ['🤝', 'apretón'],
  ['🙏', 'gracias'],
  ['✍️', 'escribe'],
  ['💅', 'uñas'],
  ['🤳', 'selfie'],
  ['💪', 'músculo'],
  ['🦾', 'brazo robot'],
  ['🦵', 'pierna'],
  ['🦶', 'pie'],
  ['👂', 'oreja'],
  ['🦻', 'audífono'],
  ['👃', 'nariz'],
  ['🧠', 'cerebro'],
  ['👀', 'ojos'],
  ['👁️', 'ojo'],
  ['👅', 'lengua parte'],
  ['👄', 'boca'],
]);

const PEOPLE = pack([
  ['👶', 'bebé'],
  ['👧', 'niña'],
  ['🧒', 'niño'],
  ['👦', 'chico'],
  ['👩', 'mujer'],
  ['🧑', 'persona'],
  ['👨', 'hombre'],
  ['👩‍🦱', 'mujer rizada'],
  ['👨‍🦱', 'hombre rizado'],
  ['👩‍🦰', 'mujer pelirroja'],
  ['👨‍🦰', 'hombre pelirrojo'],
  ['👩‍🦳', 'mujer canosa'],
  ['👨‍🦳', 'hombre canoso'],
  ['👩‍🦲', 'mujer calva'],
  ['👨‍🦲', 'hombre calvo'],
  ['👱‍♀️', 'rubia'],
  ['👱‍♂️', 'rubio'],
  ['🧔', 'barba'],
  ['👵', 'abuela'],
  ['👴', 'abuelo'],
  ['🙍‍♀️', 'mujer ceño'],
  ['🙎‍♀️', 'mujer puchero'],
  ['🙅‍♀️', 'no mujer'],
  ['🙅‍♂️', 'no hombre'],
  ['🙆‍♀️', 'ok mujer'],
  ['💁‍♀️', 'información'],
  ['🙋‍♀️', 'levanta mano'],
  ['🧏‍♀️', 'sorda'],
  ['🙇‍♀️', 'reverencia'],
  ['🤦‍♀️', 'facepalm'],
  ['🤷‍♀️', 'no sé'],
  ['🤷‍♂️', 'no sé hombre'],
  ['👩‍⚕️', 'doctora'],
  ['👨‍⚕️', 'doctor'],
  ['👩‍🎓', 'graduada'],
  ['👨‍🎓', 'graduado'],
  ['👩‍🏫', 'maestra'],
  ['👨‍🏫', 'maestro'],
  ['👩‍⚖️', 'jueza'],
  ['👨‍⚖️', 'juez'],
  ['👩‍🌾', 'granjera'],
  ['👨‍🌾', 'granjero'],
  ['👩‍🍳', 'chef mujer'],
  ['👨‍🍳', 'chef'],
  ['👩‍🔧', 'mecánica'],
  ['👨‍🔧', 'mecánico'],
  ['👩‍🏭', 'obrera'],
  ['👨‍🏭', 'obrero'],
  ['👩‍💼', 'oficina mujer'],
  ['👨‍💼', 'oficina'],
  ['👩‍🔬', 'científica'],
  ['👨‍🔬', 'científico'],
  ['👩‍💻', 'programadora'],
  ['👨‍💻', 'programador'],
  ['👩‍🎤', 'cantante'],
  ['👨‍🎤', 'cantante hombre'],
  ['👩‍🎨', 'artista'],
  ['👨‍🎨', 'artista hombre'],
  ['👩‍✈️', 'piloto mujer'],
  ['👨‍✈️', 'piloto'],
  ['👩‍🚀', 'astronauta mujer'],
  ['👨‍🚀', 'astronauta'],
  ['👩‍🚒', 'bombera'],
  ['👨‍🚒', 'bombero'],
  ['👮‍♀️', 'policía mujer'],
  ['👮‍♂️', 'policía'],
  ['🕵️‍♀️', 'detective mujer'],
  ['💂‍♀️', 'guardia mujer'],
  ['👷‍♀️', 'construcción mujer'],
  ['👷‍♂️', 'construcción'],
  ['🤴', 'príncipe'],
  ['👸', 'princesa'],
  ['👳‍♀️', 'turbante mujer'],
  ['👳‍♂️', 'turbante'],
  ['👲', 'gorra'],
  ['🧕', 'pañuelo'],
  ['🤵', 'esmoquin'],
  ['👰', 'novia'],
  ['🤰', 'embarazada'],
  ['🤱', 'lactancia'],
  ['👼', 'angelito'],
  ['🎅', 'santa'],
  ['🤶', 'señora santa'],
  ['🦸‍♀️', 'superheroína'],
  ['🦸‍♂️', 'superhéroe'],
  ['🦹‍♀️', 'villana'],
  ['🧙‍♀️', 'maga'],
  ['🧚‍♀️', 'hada'],
  ['🧛‍♀️', 'vampiresa'],
  ['🧛‍♂️', 'vampiro'],
  ['🧜‍♀️', 'sirena'],
  ['🧜‍♂️', 'tritón'],
  ['🧝‍♀️', 'elfa'],
  ['🧞‍♀️', 'genio mujer'],
  ['🧟‍♀️', 'zombi mujer'],
  ['🧟‍♂️', 'zombi'],
  ['💃', 'bailarina'],
  ['🕺', 'bailarín'],
  ['🕴️', 'traje levitando'],
  ['👯‍♀️', 'bailarinas'],
  ['🚶‍♀️', 'camina mujer'],
  ['🚶‍♂️', 'camina'],
  ['🏃‍♀️', 'corre mujer'],
  ['🏃‍♂️', 'corre'],
  ['👩‍❤️‍👨', 'pareja corazón'],
  ['👩‍❤️‍👩', 'pareja mujeres'],
  ['👨‍❤️‍👨', 'pareja hombres'],
  ['💑', 'pareja'],
  ['👩‍❤️‍💋‍👨', 'beso pareja'],
  ['👪', 'familia'],
  ['👨‍👩‍👧', 'familia 2'],
  ['👨‍👩‍👧‍👦', 'familia 3'],
  ['👩‍👩‍👦', 'familia mujeres'],
  ['👨‍👨‍👦', 'familia hombres'],
  ['👤', 'silueta'],
  ['👥', 'siluetas'],
  ['🫂', 'abrazos'],
]);

const OBJECTS = pack([
  ['👓', 'gafas'],
  ['🕶️', 'lentes sol'],
  ['🥽', 'goggles'],
  ['🥼', 'bata'],
  ['🦺', 'chaleco'],
  ['👔', 'corbata'],
  ['👕', 'camisa'],
  ['👖', 'jeans'],
  ['🧣', 'bufanda'],
  ['🧤', 'guantes'],
  ['🧥', 'abrigo'],
  ['🧦', 'calcetines'],
  ['👗', 'vestido'],
  ['👘', 'kimono'],
  ['🥻', 'sari'],
  ['🩱', 'traje baño'],
  ['🩲', 'trusa'],
  ['🩳', 'shorts'],
  ['👙', 'bikini'],
  ['👚', 'blusa'],
  ['👛', 'monedero'],
  ['👜', 'bolso'],
  ['👝', 'clutch'],
  ['🎒', 'mochila'],
  ['👞', 'zapato'],
  ['👟', 'tenis'],
  ['🥾', 'bota trekking'],
  ['🥿', 'bailarina zapato'],
  ['👠', 'tacón'],
  ['👡', 'sandalia'],
  ['🩰', 'ballet'],
  ['👢', 'bota'],
  ['👑', 'corona'],
  ['👒', 'sombrero sol'],
  ['🎩', 'sombrero copa'],
  ['🎓', 'birrete'],
  ['🧢', 'gorra'],
  ['🪖', 'casco'],
  ['💄', 'labial'],
  ['💍', 'anillo'],
  ['💼', 'maletín'],
  ['☂️', 'paraguas'],
]);

const NATURE = pack([
  ['🐶', 'perro'],
  ['🐱', 'gato'],
  ['🐭', 'ratón'],
  ['🐹', 'hámster'],
  ['🐰', 'conejo'],
  ['🐻', 'oso'],
  ['🐼', 'panda'],
  ['🐨', 'koala'],
  ['🐯', 'tigre cara'],
  ['🦁', 'león'],
  ['🐮', 'vaca cara'],
  ['🐷', 'cerdo cara'],
  ['🐽', 'hocico'],
  ['🐸', 'rana'],
  ['🙈', 'mono no ve'],
  ['🙉', 'mono no oye'],
  ['🙊', 'mono no habla'],
  ['🐒', 'mono'],
  ['🦍', 'gorila'],
  ['🦧', 'orangután'],
  ['🐔', 'pollo'],
  ['🐧', 'pingüino'],
  ['🐦', 'pájaro'],
  ['🐤', 'pollito'],
  ['🐣', 'pollito cascarón'],
  ['🐥', 'pollito frente'],
  ['🐺', 'lobo'],
  ['🦊', 'zorro'],
  ['🦝', 'mapache'],
  ['🐗', 'jabalí'],
  ['🐴', 'caballo cara'],
  ['🦓', 'cebra'],
  ['🦒', 'jirafa'],
  ['🦌', 'ciervo'],
  ['🦄', 'unicornio'],
  ['🐝', 'abeja'],
  ['🐛', 'oruga'],
  ['🦋', 'mariposa'],
  ['🐌', 'caracol'],
  ['🐞', 'mariquita'],
  ['🐜', 'hormiga'],
  ['🦗', 'grillo'],
  ['🕷️', 'araña'],
  ['🕸️', 'telaraña'],
  ['🦂', 'escorpión'],
  ['🦟', 'mosquito'],
  ['🐢', 'tortuga'],
  ['🐍', 'serpiente'],
  ['🦎', 'lagarto'],
  ['🦀', 'cangrejo'],
  ['🦞', 'langosta'],
  ['🐙', 'pulpo'],
  ['🦑', 'calamar'],
  ['🦐', 'camarón'],
  ['🐠', 'pez tropical'],
  ['🐟', 'pez'],
  ['🐡', 'pez globo'],
  ['🐬', 'delfín'],
  ['🦈', 'tiburón'],
  ['🐳', 'ballena chorro'],
  ['🐋', 'ballena'],
  ['🐊', 'cocodrilo'],
  ['🐆', 'leopardo'],
  ['🐅', 'tigre'],
  ['🐃', 'búfalo'],
  ['🐂', 'buey'],
  ['🐄', 'vaca'],
  ['🐪', 'camello'],
  ['🐫', 'dromedario'],
  ['🐘', 'elefante'],
  ['🦏', 'rinoceronte'],
  ['🦛', 'hipopótamo'],
  ['🐏', 'carnero'],
  ['🐑', 'oveja'],
  ['🐐', 'cabra'],
  ['🐎', 'caballo'],
  ['🐖', 'cerdo'],
  ['🦇', 'murciélago'],
  ['🐓', 'gallo'],
  ['🦃', 'pavo'],
  ['🕊️', 'paloma'],
  ['🦅', 'águila'],
  ['🦆', 'pato'],
  ['🦉', 'búho'],
  ['🦢', 'cisne'],
  ['🦩', 'flamenco'],
  ['🦚', 'pavo real'],
  ['🦜', 'loro'],
  ['🐩', 'caniche'],
  ['🐈', 'gato cuerpo'],
  ['🐇', 'conejo cuerpo'],
  ['🐁', 'ratón cuerpo'],
  ['🐀', 'rata'],
  ['🐿️', 'ardilla'],
  ['🦔', 'erizo'],
  ['🦘', 'canguro'],
  ['🦡', 'tejón'],
  ['🦙', 'llama'],
  ['🦥', 'perezoso'],
  ['🦦', 'nutria'],
  ['🦨', 'mofeta'],
  ['🐾', 'huellas'],
  ['🐲', 'dragón cara'],
  ['🐉', 'dragón'],
  ['🦕', 'saurópodo'],
  ['🦖', 't-rex'],
  ['🌵', 'cactus'],
  ['🎄', 'árbol navidad'],
  ['🌲', 'pino'],
  ['🌳', 'árbol'],
  ['🌴', 'palmera'],
  ['🌱', 'brote'],
  ['🌿', 'hierba'],
  ['☘️', 'trébol'],
  ['🍀', 'trébol 4'],
  ['🎍', 'bambú'],
  ['🎋', 'tanabata'],
  ['🍃', 'hoja viento'],
  ['🍂', 'hoja seca'],
  ['🍁', 'maple'],
  ['🌾', 'arroz'],
  ['🌺', 'hibisco'],
  ['🌻', 'girasol'],
  ['🌹', 'rosa'],
  ['🥀', 'rosa marchita'],
  ['🌷', 'tulipán'],
  ['🌼', 'margarita'],
  ['🌸', 'cerezo'],
  ['💐', 'ramo'],
  ['🍄', 'hongo'],
  ['🌰', 'castaña'],
  ['🐚', 'concha'],
  ['🌎', 'tierra américas'],
  ['🌍', 'tierra áfrica'],
  ['🌏', 'tierra asia'],
  ['🌑', 'luna nueva'],
  ['🌒', 'luna creciente'],
  ['🌓', 'cuarto creciente'],
  ['🌔', 'gibosa creciente'],
  ['🌕', 'luna llena'],
  ['🌖', 'gibosa menguante'],
  ['🌗', 'cuarto menguante'],
  ['🌘', 'luna menguante'],
  ['🌚', 'luna nueva cara'],
  ['🌝', 'luna llena cara'],
  ['🌛', 'luna cuarto cara'],
  ['🌜', 'luna menguante cara'],
  ['🌞', 'sol cara'],
  ['🌙', 'media luna'],
  ['☀️', 'sol'],
  ['⭐', 'estrella'],
  ['🌟', 'estrella brillo'],
  ['🌠', 'estrella fugaz'],
  ['✨', 'brillos'],
  ['☄️', 'cometa'],
  ['🌤️', 'sol nube'],
  ['⛅', 'nublado'],
  ['🌥️', 'nube grande'],
  ['🌦️', 'sol lluvia'],
  ['🌧️', 'lluvia'],
  ['🌨️', 'nieve nube'],
  ['🌩️', 'rayo nube'],
  ['⚡', 'rayo'],
  ['🔥', 'fuego'],
  ['💥', 'boom'],
  ['❄️', 'copo'],
  ['☃️', 'muñeco nieve'],
  ['⛄', 'muñeco'],
  ['🌬️', 'viento'],
  ['💨', 'ráfaga'],
  ['🌪️', 'tornado'],
  ['🌫️', 'niebla'],
  ['☔', 'paraguas lluvia'],
  ['💧', 'gota'],
  ['💦', 'gotas'],
  ['🌊', 'ola'],
]);

const FOOD = pack([
  ['🍏', 'manzana verde'],
  ['🍎', 'manzana'],
  ['🍐', 'pera'],
  ['🍊', 'naranja'],
  ['🍋', 'limón'],
  ['🍌', 'plátano'],
  ['🍉', 'sandía'],
  ['🍇', 'uvas'],
  ['🍓', 'fresa'],
  ['🍈', 'melón'],
  ['🍒', 'cerezas'],
  ['🍑', 'durazno'],
  ['🥭', 'mango'],
  ['🍍', 'piña'],
  ['🥥', 'coco'],
  ['🥝', 'kiwi'],
  ['🍅', 'tomate'],
  ['🥑', 'aguacate'],
  ['🍆', 'berenjena'],
  ['🌶️', 'chile'],
  ['🥒', 'pepino'],
  ['🥬', 'lechuga'],
  ['🥦', 'brócoli'],
  ['🌽', 'maíz'],
  ['🥕', 'zanahoria'],
  ['🥗', 'ensalada'],
  ['🥔', 'papa'],
  ['🍠', 'camote'],
  ['🥜', 'maní'],
  ['🍞', 'pan'],
  ['🥐', 'croissant'],
  ['🥖', 'baguette'],
  ['🥨', 'pretzel'],
  ['🥯', 'bagel'],
  ['🥞', 'pancakes'],
  ['🧇', 'waffle'],
  ['🧀', 'queso'],
  ['🍗', 'muslo'],
  ['🍖', 'carne hueso'],
  ['🥩', 'corte'],
  ['🍤', 'camarón frito'],
  ['🍳', 'huevo frito'],
  ['🥚', 'huevo'],
  ['🥓', 'tocino'],
  ['🍔', 'hamburguesa'],
  ['🍟', 'papas'],
  ['🌭', 'hot dog'],
  ['🍕', 'pizza'],
  ['🍝', 'pasta'],
  ['🥪', 'sándwich'],
  ['🌮', 'taco'],
  ['🌯', 'burrito'],
  ['🥙', 'pita'],
  ['🍜', 'ramen'],
  ['🍲', 'sopa'],
  ['🥫', 'lata'],
  ['🍣', 'sushi'],
  ['🍱', 'bento'],
  ['🍛', 'curry'],
  ['🍙', 'onigiri'],
  ['🍚', 'arroz'],
  ['🍘', 'galleta arroz'],
  ['🍥', 'naruto'],
  ['🥠', 'galleta fortuna'],
  ['🍢', 'oden'],
  ['🍡', 'dango'],
  ['🍧', 'raspado'],
  ['🍨', 'helado copa'],
  ['🍦', 'cono'],
  ['🥧', 'pay'],
  ['🧁', 'cupcake'],
  ['🍰', 'rebanada'],
  ['🎂', 'pastel'],
  ['🍮', 'flan'],
  ['🍭', 'paleta'],
  ['🍬', 'dulce'],
  ['🍫', 'chocolate'],
  ['🍿', 'palomitas'],
  ['🍩', 'dona'],
  ['🍪', 'galleta'],
  ['🍯', 'miel'],
  ['☕', 'café'],
  ['🍵', 'té'],
  ['🧃', 'jugo'],
  ['🥤', 'refresco'],
  ['🧋', 'bubble tea'],
  ['🍶', 'sake'],
  ['🍼', 'biberón'],
  ['🥛', 'leche'],
  ['🍺', 'cerveza'],
  ['🍻', 'brindis cerveza'],
  ['🍷', 'vino'],
  ['🍸', 'cocktail'],
  ['🍹', 'tropical'],
  ['🥃', 'whisky'],
  ['🍾', 'champaña'],
  ['🥄', 'cuchara'],
  ['🍴', 'cubiertos'],
  ['🍽️', 'plato'],
  ['🥢', 'palillos'],
]);

const ACTIVITY = pack([
  ['⚽', 'fútbol'],
  ['🏀', 'básquet'],
  ['🏈', 'americano'],
  ['⚾', 'béisbol'],
  ['🥎', 'softbol'],
  ['🎾', 'tenis'],
  ['🏐', 'vóley'],
  ['🏉', 'rugby'],
  ['🥏', 'frisbee'],
  ['🎱', 'billar'],
  ['🏓', 'ping pong'],
  ['🏸', 'bádminton'],
  ['🥅', 'portería'],
  ['🏒', 'hockey hielo'],
  ['🏑', 'hockey'],
  ['🥍', 'lacrosse'],
  ['🏏', 'cricket'],
  ['🥌', 'curling'],
  ['⛳', 'golf'],
  ['🏹', 'arco'],
  ['🎣', 'pesca'],
  ['🥊', 'box'],
  ['🥋', 'kimono deporte'],
  ['⛸️', 'patín hielo'],
  ['🎿', 'esquí'],
  ['🏂', 'snowboard'],
  ['🪂', 'paracaídas'],
  ['🏊', 'nada'],
  ['🏄', 'surf'],
  ['🚣', 'remo'],
  ['🏇', 'equitación'],
  ['🚴', 'bici'],
  ['🚵', 'bici montaña'],
  ['🏃', 'corre'],
  ['🚶', 'camina'],
  ['🏋️', 'pesas'],
  ['🤸', 'giro'],
  ['🤺', 'esgrima'],
  ['🤼', 'lucha'],
  ['🤽', 'waterpolo'],
  ['🤾', 'balonmano'],
  ['🤹', 'malabares'],
  ['🧘', 'yoga'],
  ['🥇', 'oro'],
  ['🥈', 'plata'],
  ['🥉', 'bronce'],
  ['🏆', 'trofeo'],
  ['🏅', 'medalla'],
  ['🎖️', 'condecoración'],
  ['🎗️', 'lazo'],
  ['🎟️', 'ticket'],
  ['🎫', 'boleto'],
  ['🎪', 'circo'],
  ['🎭', 'teatro'],
  ['🎨', 'paleta'],
  ['🎬', 'claqueta'],
  ['🎤', 'micrófono'],
  ['🎧', 'audífonos'],
  ['🎼', 'partitura'],
  ['🎵', 'nota'],
  ['🎶', 'notas'],
  ['🎹', 'piano'],
  ['🥁', 'tambor'],
  ['🎷', 'saxo'],
  ['🎺', 'trompeta'],
  ['🎸', 'guitarra'],
  ['🎻', 'violín'],
  ['🎲', 'dado'],
  ['🎯', 'darts'],
  ['🎳', 'bolos'],
  ['🎮', 'control'],
  ['🕹️', 'joystick'],
  ['👾', 'arcade'],
  ['🎰', 'tragamonedas'],
  ['🧩', 'puzzle'],
  ['♟️', 'ajedrez'],
]);

const TRAVEL = pack([
  ['🚗', 'auto'],
  ['🚕', 'taxi'],
  ['🚙', 'suv'],
  ['🚌', 'bus'],
  ['🚎', 'trolebús'],
  ['🏎️', 'carrera'],
  ['🚓', 'patrulla'],
  ['🚑', 'ambulancia'],
  ['🚒', 'bomberos'],
  ['🚐', 'van'],
  ['🚚', 'camión'],
  ['🚛', 'tráiler'],
  ['🚜', 'tractor'],
  ['🛴', 'scooter'],
  ['🛵', 'moto scooter'],
  ['🏍️', 'moto'],
  ['🚲', 'bicicleta'],
  ['🛺', 'mototaxi'],
  ['🚂', 'locomotora'],
  ['🚃', 'vagón'],
  ['🚄', 'tren bala'],
  ['🚅', 'shinkansen'],
  ['🚆', 'tren'],
  ['🚇', 'metro'],
  ['🚈', 'ligero'],
  ['🚉', 'estación'],
  ['🚊', 'tranvía'],
  ['🚝', 'monorriel'],
  ['🚞', 'montaña tren'],
  ['🚟', 'suspendido'],
  ['🚠', 'teleférico'],
  ['🚡', 'aéreo'],
  ['✈️', 'avión'],
  ['🛩️', 'avioneta'],
  ['🛫', 'despegue'],
  ['🛬', 'aterrizaje'],
  ['💺', 'asiento'],
  ['🚀', 'cohete'],
  ['🛸', 'ovni'],
  ['🚁', 'helicóptero'],
  ['🛶', 'canoa'],
  ['⛵', 'velero'],
  ['🚤', 'lancha'],
  ['🛥️', 'yate'],
  ['🛳️', 'crucero'],
  ['⛴️', 'ferry'],
  ['🚢', 'barco'],
  ['⚓', 'ancla'],
  ['🚧', 'obras'],
  ['🚦', 'semáforo'],
  ['🚥', 'semáforo horizontal'],
  ['🛑', 'alto'],
  ['⛽', 'gasolina'],
  ['🗺️', 'mapa'],
  ['🗿', 'moái'],
  ['🗽', 'libertad'],
  ['🗼', 'tokyo tower'],
  ['🏰', 'castillo'],
  ['🏯', 'castillo japonés'],
  ['🏟️', 'estadio'],
  ['🎡', 'noria'],
  ['🎢', 'montaña rusa'],
  ['🎠', 'carrusel'],
  ['⛲', 'fuente'],
  ['⛱️', 'sombrilla playa'],
  ['🏖️', 'playa'],
  ['🏝️', 'isla'],
  ['🏜️', 'desierto'],
  ['🌋', 'volcán'],
  ['⛰️', 'montaña'],
  ['🏔️', 'nevada'],
  ['🗻', 'fuji'],
  ['🏕️', 'campamento'],
  ['⛺', 'tienda'],
  ['🏠', 'casa'],
  ['🏡', 'casa jardín'],
  ['🏘️', 'casas'],
  ['🏚️', 'abandonada'],
  ['🏗️', 'construcción'],
  ['🏭', 'fábrica'],
  ['🏢', 'edificio'],
  ['🏬', 'tienda'],
  ['🏣', 'correo jp'],
  ['🏤', 'correo'],
  ['🏥', 'hospital'],
  ['🏦', 'banco'],
  ['🏨', 'hotel'],
  ['🏪', 'conveniencia'],
  ['🏫', 'escuela'],
  ['🏩', 'love hotel'],
  ['💒', 'boda'],
  ['⛪', 'iglesia'],
  ['🕌', 'mezquita'],
  ['🕍', 'sinagoga'],
  ['🕋', 'kaaba'],
  ['⛩️', 'torii'],
  ['🌉', 'puente'],
  ['🌃', 'noche'],
  ['🌆', 'atardecer ciudad'],
  ['🌇', 'puesta sol'],
  ['🏙️', 'skyline'],
  ['🌌', 'vía láctea'],
  ['🎇', 'bengala'],
  ['🎆', 'fuegos'],
  ['🌈', 'arcoíris'],
  ['🗾', 'japón mapa'],
]);

const THINGS = pack([
  ['⌚', 'reloj'],
  ['📱', 'celular'],
  ['📲', 'celular flecha'],
  ['💻', 'laptop'],
  ['⌨️', 'teclado'],
  ['🖥️', 'monitor'],
  ['🖨️', 'impresora'],
  ['🖱️', 'mouse'],
  ['🖲️', 'trackball'],
  ['🕹️', 'palanca'],
  ['💾', 'disquete'],
  ['💿', 'cd'],
  ['📀', 'dvd'],
  ['📼', 'vhs'],
  ['📷', 'cámara'],
  ['📸', 'flash'],
  ['📹', 'videocámara'],
  ['🎥', 'cine'],
  ['📽️', 'proyector'],
  ['📞', 'auricular'],
  ['☎️', 'teléfono'],
  ['📟', 'pager'],
  ['📠', 'fax'],
  ['📺', 'tv'],
  ['📻', 'radio'],
  ['🎙️', 'estudio'],
  ['🔦', 'linterna'],
  ['🕯️', 'vela'],
  ['💡', 'foco'],
  ['🗑️', 'basura'],
  ['🛒', 'carrito'],
  ['🔨', 'martillo'],
  ['⛏️', 'pico'],
  ['⚒️', 'herramientas'],
  ['🛠️', 'llave martillo'],
  ['🗡️', 'daga'],
  ['⚔️', 'espadas'],
  ['🔫', 'pistola agua'],
  ['🛡️', 'escudo'],
  ['🔧', 'llave'],
  ['🔩', 'tornillo'],
  ['⚙️', 'engranaje'],
  ['⛓️', 'cadena'],
  ['🧰', 'caja herramientas'],
  ['🧲', 'imán'],
  ['💣', 'bomba'],
  ['🔪', 'cuchillo'],
  ['💈', 'barbería'],
  ['🔮', 'bola cristal'],
  ['🔭', 'telescopio'],
  ['🔬', 'microscopio'],
  ['💊', 'pastilla'],
  ['💉', 'jeringa'],
  ['🩹', 'curita'],
  ['🩺', 'estetoscopio'],
  ['🌡️', 'termómetro'],
  ['🏷️', 'etiqueta'],
  ['🚽', 'inodoro'],
  ['🛁', 'bañera'],
  ['🚿', 'ducha'],
  ['🧴', 'botella'],
  ['🔑', 'llave puerta'],
  ['🗝️', 'llave antigua'],
  ['🛋️', 'sofá'],
  ['🛏️', 'cama'],
  ['🚪', 'puerta'],
  ['🪞', 'espejo'],
  ['🪟', 'ventana'],
  ['🛎️', 'campana hotel'],
  ['🧭', 'brújula'],
  ['🎈', 'globo'],
  ['🎁', 'regalo'],
  ['🎀', 'moño'],
  ['🎊', 'confeti'],
  ['🎉', 'fiesta'],
  ['✉️', 'sobre'],
  ['📧', 'email'],
  ['📦', 'paquete'],
  ['📫', 'buzón'],
  ['📮', 'buzón correo'],
  ['✏️', 'lápiz'],
  ['✒️', 'pluma'],
  ['🖊️', 'bolígrafo'],
  ['🖌️', 'pincel'],
  ['📝', 'nota'],
  ['📁', 'carpeta'],
  ['📅', 'calendario'],
  ['📌', 'chinche'],
  ['📎', 'clip'],
  ['📏', 'regla'],
  ['📐', 'escuadra'],
  ['✂️', 'tijeras'],
  ['🔒', 'candado'],
  ['🔓', 'abierto'],
  ['🔔', 'campana'],
  ['📣', 'megáfono'],
  ['📢', 'altavoz'],
]);

const SYMBOLS = pack([
  ['❤️', 'corazón'],
  ['🧡', 'corazón naranja'],
  ['💛', 'corazón amarillo'],
  ['💚', 'corazón verde'],
  ['💙', 'corazón azul'],
  ['💜', 'corazón morado'],
  ['🖤', 'corazón negro'],
  ['🤍', 'corazón blanco'],
  ['🤎', 'corazón café'],
  ['💔', 'roto'],
  ['❣️', 'exclamación corazón'],
  ['💕', 'dos corazones'],
  ['💞', 'girando'],
  ['💓', 'latido'],
  ['💗', 'creciendo'],
  ['💖', 'brillo corazón'],
  ['💘', 'flecha corazón'],
  ['💝', 'regalo corazón'],
  ['💟', 'adorno corazón'],
  ['♈', 'aries'],
  ['♉', 'tauro'],
  ['♊', 'géminis'],
  ['♋', 'cáncer'],
  ['♌', 'leo'],
  ['♍', 'virgo'],
  ['♎', 'libra'],
  ['♏', 'escorpio'],
  ['♐', 'sagitario'],
  ['♑', 'capricornio'],
  ['♒', 'acuario'],
  ['♓', 'piscis'],
  ['⛎', 'ofiuco'],
  ['✝️', 'cruz'],
  ['☪️', 'luna estrella'],
  ['🕉️', 'om'],
  ['☸️', 'dharma'],
  ['✡️', 'estrella david'],
  ['🔯', 'hexagrama'],
  ['🕎', 'menorá'],
  ['☯️', 'yin yang'],
  ['☦️', 'ortodoxa'],
  ['🛐', 'culto'],
  ['⚛️', 'átomo'],
  ['☮️', 'paz'],
  ['☢️', 'radiactivo'],
  ['☣️', 'biohazard'],
  ['⚠️', 'alerta'],
  ['⛔', 'no entrar'],
  ['🚫', 'prohibido'],
  ['❌', 'equis'],
  ['⭕', 'círculo'],
  ['💯', 'cien'],
  ['🔴', 'rojo'],
  ['🟠', 'naranja'],
  ['🟡', 'amarillo'],
  ['🟢', 'verde'],
  ['🔵', 'azul'],
  ['🟣', 'morado'],
  ['⚫', 'negro'],
  ['⚪', 'blanco'],
  ['🟤', 'café'],
  ['🔶', 'rombo naranja'],
  ['🔷', 'rombo azul'],
  ['🔸', 'rombo chico naranja'],
  ['🔹', 'rombo chico azul'],
  ['🔺', 'triángulo'],
  ['🔻', 'triángulo abajo'],
  ['💠', 'diamante'],
  ['🔘', 'botón'],
  ['🔳', 'cuadrado claro'],
  ['🔲', 'cuadrado oscuro'],
  ['▶️', 'play'],
  ['⏸️', 'pausa'],
  ['⏹️', 'stop'],
  ['⏺️', 'rec'],
  ['⏭️', 'siguiente'],
  ['⏮️', 'anterior'],
  ['⏩', 'adelantar'],
  ['⏪', 'atrasar'],
  ['🔀', 'aleatorio'],
  ['🔁', 'repetir'],
  ['🔂', 'repetir uno'],
  ['⬆️', 'arriba'],
  ['⬇️', 'abajo'],
  ['⬅️', 'izquierda'],
  ['➡️', 'derecha'],
  ['↗️', 'noreste'],
  ['↘️', 'sureste'],
  ['↙️', 'suroeste'],
  ['↖️', 'noroeste'],
  ['↕️', 'vertical'],
  ['↔️', 'horizontal'],
  ['↩️', 'retorno'],
  ['↪️', 'avance'],
  ['0️⃣', 'cero'],
  ['1️⃣', 'uno'],
  ['2️⃣', 'dos'],
  ['3️⃣', 'tres'],
  ['4️⃣', 'cuatro'],
  ['5️⃣', 'cinco'],
  ['6️⃣', 'seis'],
  ['7️⃣', 'siete'],
  ['8️⃣', 'ocho'],
  ['9️⃣', 'nueve'],
  ['🔟', 'diez'],
  ['🅰️', 'a'],
  ['🅱️', 'b'],
  ['🆎', 'ab'],
  ['🅾️', 'o'],
  ['🆘', 'sos'],
  ['🆑', 'cl'],
  ['🅿️', 'parking'],
  ['♿', 'accesible'],
  ['🏧', 'cajero'],
  ['🚾', 'wc'],
  ['🚹', 'hombres'],
  ['🚺', 'mujeres'],
  ['🚻', 'baños'],
  ['🚮', 'basura símbolo'],
  ['🚰', 'agua'],
  ['🕐', '1'],
  ['🕑', '2'],
  ['🕒', '3'],
  ['🕓', '4'],
  ['🕔', '5'],
  ['🕕', '6'],
  ['🕖', '7'],
  ['🕗', '8'],
  ['🕘', '9'],
  ['🕙', '10'],
  ['🕚', '11'],
  ['🕛', '12'],
  ['💬', 'globo'],
  ['💭', 'pensamiento'],
  ['🗯️', 'enojo globo'],
  ['💤', 'zzz'],
  ['💢', 'enojo'],
  ['💮', 'sello'],
  ['🔔', 'campana símbolo'],
  ['🔕', 'silencio'],
  ['📣', 'anuncio'],
  ['🔊', 'volumen'],
  ['🔇', 'mute'],
  ['🈁', 'aquí'],
  ['🈯', 'reservado'],
  ['🉐', 'ganga'],
  ['🈹', 'descuento'],
  ['🈲', 'prohibido jp'],
  ['🈶', 'de pago'],
  ['🈚', 'gratis'],
  ['🈸', 'aplicación'],
  ['🈺', 'abierto jp'],
  ['🈷️', 'mensual'],
  ['🈴', 'aprobado'],
  ['🈵', 'lleno'],
  ['🈳', 'vacante'],
  ['🈂️', 'servicio'],
  ['㊗️', 'felicidades'],
  ['㊙️', 'secreto'],
]);

const FLAGS = FLAG_PICKER_EMOJIS;

export const UNICODE_EMOJI_CATEGORIES: UnicodeEmojiCategory[] = [
  { id: 'faces', label: 'Caras', icon: '😀', emojis: FACES },
  { id: 'hands', label: 'Gestos', icon: '👋', emojis: HANDS },
  { id: 'people', label: 'Personas', icon: '👤', emojis: PEOPLE },
  { id: 'nature', label: 'Naturaleza', icon: '🐶', emojis: NATURE },
  { id: 'food', label: 'Comida', icon: '🍕', emojis: FOOD },
  { id: 'activity', label: 'Actividades', icon: '⚽', emojis: ACTIVITY },
  { id: 'travel', label: 'Viajes', icon: '✈️', emojis: TRAVEL },
  { id: 'objects', label: 'Ropa', icon: '👕', emojis: OBJECTS },
  { id: 'things', label: 'Objetos', icon: '💡', emojis: THINGS },
  { id: 'symbols', label: 'Símbolos', icon: '❤️', emojis: SYMBOLS },
  { id: 'flags', label: 'Banderas', icon: '🏁', emojis: FLAGS },
];

export function filterUnicodeEmojis(list: readonly UnicodeEmoji[], query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return list;
  return list.filter((emoji) => emoji.label.includes(q) || emoji.char.includes(q));
}
